// message reducer
export const MESSAGE_SET = "MESSAGE_SET";

//middleware
export const USER_MESSAGE_CREATE_REQUEST = "USER_MESSAGE_CREATE_REQUEST";
export const USER_MESSAGE_FETCH_REQUEST = "USER_MESSAGE_FETCH_REQUEST";
export const USER_MESSAGE_DELETE_REQUEST = "USER_MESSAGE_DELETE_REQUEST";