//room reducer
export const ROOM_SET = "ROOM_SET";

//middleware from user
export const USER_ROOM_CREATE_REQUEST = "USER_ROOM_CREATE_REQUEST";
export const USER_ROOM_FETCH_REQUEST = "USER_ROOM_FETCH_REQUEST";
export const USER_ROOM_JOIN_REQUEST = "USER_ROOM_JOIN_REQUEST";
export const USER_ROOM_DELETE_REQUEST = "USER_ROOM_DELETE_REQUEST";
export const USER_ROOM_LEAVE_REQUEST = "USER_ROOM_LEAVE_REQUEST";
export const USER_ROOM_EDIT_REQUEST = "USER_ROOM_EDIT_REQUEST";
export const USER_PARTICIPANT_FETCH_REQUEST = "USER_PARTICIPANT_FETCH_REQUEST";