// authorise
export const AUTHORISE_USER = "AUTHORISE_USER";
export const AUTHORISE_USER_SUCCESS = "AUTHORISE_USER_SUCCESS";
export const AUTHORISE_USER_ERROR = "AUTHORISE_USER_ERROR";

// forgotten password
export const FORGOTTEN_PASSWORD = "FORGOTTEN_PASSWORD";
export const FORGOTTEN_PASSWORD_SUCCESS = "FORGOTTEN_PASSWORD_SUCCESS";
export const FORGOTTEN_PASSWORD_ERROR = "FORGOTTEN_PASSWORD_ERROR";

// password reset
export const PASSWORD_RESET = "PASSWORD_RESET";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_ERROR = "PASSWORD_RESET_ERROR";

// signup
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

// stat
export const STAT_FETCH = "STAT_FETCH";
export const STAT_FETCH_SUCCESS = "STAT_FETCH_SUCCESS";
export const STAT_FETCH_ERROR = "STAT_FETCH_ERROR";

// room
export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_CREATE_ERROR = "ROOM_CREATE_ERROR";

export const ROOM_USER_FETCH = "ROOM_USER_FETCH";
export const ROOM_USER_FETCH_SUCCESS = "ROOM_USER_FETCH_SUCCESS";
export const ROOM_USER_FETCH_ERROR = "ROOM_USER_FETCH_ERROR";

export const ROOM_DELETE = "ROOM_DELETE";
export const ROOM_DELETE_SUCCESS = "ROOM_DELETE_SUCCESS";
export const ROOM_DELETE_ERROR = "ROOM_DELETE_ERROR";

export const ROOM_LEAVE = "ROOM_LEAVE";
export const ROOM_LEAVE_SUCCESS = "ROOM_LEAVE_SUCCESS";
export const ROOM_LEAVE_ERROR = "ROOM_LEAVE_ERROR";

export const ROOM_JOIN = "ROOM_JOIN";
export const ROOM_JOIN_SUCCESS = "ROOM_JOIN_SUCCESS";
export const ROOM_JOIN_ERROR = "ROOM_JOIN_ERROR";

export const ROOM_EDIT = "ROOM_EDIT";
export const ROOM_EDIT_SUCCESS = "ROOM_EDIT_SUCCESS";
export const ROOM_EDIT_ERROR = "ROOM_EDIT_ERROR";

export const ROOM_PARTICIPANT_JOIN = "ROOM_PARTICIPANT_JOIN";
export const ROOM_PARTICIPANT_DESTROY = "ROOM_PARTICIPANT_DESTROY";
export const ROOM_PARTICIPANT_LEAVE = "ROOM_PARTICIPANT_LEAVE";
export const ROOM_PARTICIPANT_UPDATE = "ROOM_PARTICIPANT_UPDATE";

export const MESSAGE_PARTICIPANT_CREATE = "MESSAGE_PARTICIPANT_CREATE";

// message
export const MESSAGE_CREATE = "MESSAGE_CREATE";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const MESSAGE_CREATE_ERROR = "MESSAGE_CREATE_ERROR";

export const MESSAGE_FETCH = "MESSAGE_FETCH";
export const MESSAGE_FETCH_SUCCESS = "MESSAGE_FETCH_SUCCESS";
export const MESSAGE_FETCH_ERROR = "MESSAGE_FETCH_ERROR";

export const MESSAGE_DELETE = "MESSAGE_DELETE";
export const MESSAGE_DELETE_SUCCESS = "MESSAGE_DELETE_SUCCESS";
export const MESSAGE_DELETE_ERROR = "MESSAGE_DELETE_ERROR";

// participant
export const PARTICIPANT_FETCH = "PARTICIPANT_FETCH";
export const PARTICIPANT_FETCH_SUCCESS = "PARTICIPANT_FETCH_SUCCESS";
export const PARTICIPANT_FETCH_ERROR = "PARTICIPANT_FETCH_ERROR";

// token
export const __INVALID_TOKEN__ = "__INVALID_TOKEN__";