version: '2'
services:
  titan:
    build: ../
    ports:
     - "3000:3000"
     - "3001:3001"
    volumes:
     - ../:/app
    environment:
      - NODE_ENV=development
      - SERVER_ADDRESS=http://dev.apollo.co.uk
      - SERVER_PORT=3001
      - DB_HOST=172.19.0.1
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=apollo
      - DB_PORT=3307
      - JSWT_SECRET=poolio
      - SEND_EMAIL_HOST=smtp.gmail.com
      - SEND_EMAIL_PORT=587
      - SEND_EMAIL_SECURE=false
      - SEND_EMAIL_ADDRESS=test@test.com
      - SEND_EMAIL_PASSWORD=test
    command: sh docker/development-build.sh
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=apollo
    volumes:
      - titan-datavolume:/var/lib/mysql
volumes:
  titan-datavolume: