export const AUTHORISE_USER = "AUTHORISE_USER";
export const AUTHORISE_USER_SUCCESS = "AUTHORISE_USER_SUCCESS";
export const AUTHORISE_USER_FAIL = "AUTHORISE_USER_FAIL";
export const AUTHORISE_USER_ERROR = "AUTHORISE_USER_ERROR";