export const MESSAGE_CREATE = "MESSAGE_CREATE";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const MESSAGE_CREATE_ERROR = "MESSAGE_CREATE_ERROR";

export const MESSAGE_FETCH = "MESSAGE_FETCH";
export const MESSAGE_FETCH_SUCCESS = "MESSAGE_FETCH_SUCCESS";
export const MESSAGE_FETCH_ERROR = "MESSAGE_FETCH_ERROR";

export const MESSAGE_DELETE = "MESSAGE_DELETE";
export const MESSAGE_DELETE_SUCCESS = "MESSAGE_DELETE_SUCCESS";
export const MESSAGE_DELETE_ERROR = "MESSAGE_DELETE_ERROR";

export const MESSAGE_PARTICIPANT_CREATE = "MESSAGE_PARTICIPANT_CREATE";
export const MESSAGE_PARTICIPANT_DELETE = "MESSAGE_PARTICIPANT_DELETE";