export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_CREATE_ERROR = "ROOM_CREATE_ERROR";

export const ROOM_USER_FETCH = "ROOM_USER_FETCH";
export const ROOM_USER_FETCH_SUCCESS = "ROOM_USER_FETCH_SUCCESS";
export const ROOM_USER_FETCH_ERROR = "ROOM_USER_FETCH_ERROR";

export const ROOM_DELETE = "ROOM_DELETE";
export const ROOM_DELETE_SUCCESS = "ROOM_DELETE_SUCCESS";
export const ROOM_DELETE_ERROR = "ROOM_DELETE_ERROR";

export const ROOM_LEAVE = "ROOM_LEAVE";
export const ROOM_LEAVE_SUCCESS = "ROOM_LEAVE_SUCCESS";
export const ROOM_LEAVE_ERROR = "ROOM_LEAVE_ERROR";

export const ROOM_JOIN = "ROOM_JOIN";
export const ROOM_JOIN_SUCCESS = "ROOM_JOIN_SUCCESS";
export const ROOM_JOIN_ERROR = "ROOM_JOIN_ERROR";

export const ROOM_EDIT = "ROOM_EDIT";
export const ROOM_EDIT_SUCCESS = "ROOM_EDIT_SUCCESS";
export const ROOM_EDIT_ERROR = "ROOM_EDIT_ERROR";

export const ROOM_PARTICIPANT_JOIN = "ROOM_PARTICIPANT_JOIN";
export const ROOM_PARTICIPANT_DESTROY = "ROOM_PARTICIPANT_DESTROY";
export const ROOM_PARTICIPANT_LEAVE = "ROOM_PARTICIPANT_LEAVE";
export const ROOM_PARTICIPANT_UPDATE = "ROOM_PARTICIPANT_UPDATE";